version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: php/Dockerfile
    depends_on:
      - mysql
    environment:
      APP_ENV: ${APP_ENV}
    volumes:
      - .:/var/www/symfony-docker
  nginx:
    container_name: nginx
    depends_on:
      - php
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - .:/var/www/symfony-docker/
    ports:
      - 9000:80
  mysql:
    container_name: mysql
    environment:
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: george
      MYSQL_PASSWORD: panameraflow1
      MYSQL_ROOT_PASSWORD: secret
    build:
      context: .
      dockerfile: mysql/Dockerfile
    ports:
      - 3307:3306
    volumes:
      - ./database:/var/lib/mysql